---
abstract: "Access to USF's University Network Access site"
author:
  - 'Douglas Christopher Wilson <doug@somethingdoug.com>'
build_requires:
  Test::Exception: 0.03
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-USF-UNA
no_index:
  directory:
    - inc
    - t
    - xt
provides:
  WWW::USF::UNA:
    file: lib/WWW/USF/UNA.pm
    version: 0.001
  WWW::USF::UNA::Account:
    file: lib/WWW/USF/UNA/Account.pm
    version: 0.001
requires:
  Moose: 0.89
  MooseX::StrictConstructor: 0.08
  MooseX::Types: 0.01
  MooseX::Types::Email: 0.001
  MooseX::Types::URI: 0
  Net::SAJAX: 0.102
  Scalar::Util: 0
  URI: 0
  namespace::clean: 0.04
  perl: 5.008001
resources:
  homepage: http://github.com/dougwilson/perl5-www-usf-una/
  license: http://dev.perl.org/licenses/
  repository: git://github.com/dougwilson/perl5-www-usf-una.git
version: 0.001
